apiVersion: v1
kind: Pod
metadata:
  name: optimalce-dev
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: nvcr.io/nvidia/pytorch:23.01-py3
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 32Gi
        cpu: "8"
      requests:
        nvidia.com/gpu: 1
        memory: 24Gi
        cpu: "6"
    volumeMounts:
    - name: data
      mountPath: /workspace/data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: optimalce-data
