"""Brute-force oracle: exhaustively enumerate the formula space and check the search.

This validates the WHOLE pipeline end to end -- concept masks, the quantity helpers
(`compute_quantities` / `compute_disjoint_info`, which have no independent test otherwise),
the admissible heuristic, the frontier, and the returned optimum -- without writing a second
implementation of any of it. It only needs plain numpy set operations and a max.

Space enumerated (matching what the search can return):
  * a "length" is the number of LEAVES (formula.F.__len__ sums leaves; Not delegates to its
    child, so NOT is free);
  * NOT applies only to leaves (`formula.Not.__init__` asserts `isinstance(val, Leaf)`);
  * operators are AND and OR;
  * all tree shapes, since AND/OR are associative and commutative over masks.

So for K concepts the mask set is generated by: L1 = {c, ~c}, and
L(n) = { a op b : a in L(i), b in L(n-i), op in {AND, OR} }. Enumerating masks rather than
trees means associativity/commutativity collapse for free, and the MAX over the mask set is
identical to the max over the tree set.

This is a SUPERSET-or-equal of what the search explores, so:
  oracle_max >= search_result  always;
  oracle_max == search_result  iff the search really found the optimum.
A strict inequality means the search missed the optimum -- report it, do not adjust.
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.environ.get("OPTIMALCE_UPSTREAM", os.path.expanduser("~/projects/optimalce")))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

import real_token_masks as rtm            # noqa: E402
import real_token_search as rts           # noqa: E402

FEATS = os.environ.get("FEATS", os.path.expanduser(
    "~/projects/neuron-explanations-nli/nli/data/analysis/snli_1.0_dev.feats"))


def enumerate_masks(dense, length):
    """All distinct token masks realisable by a formula of at most `length` leaves."""
    K, M = dense.shape
    lit = np.concatenate([dense, ~dense], axis=0)          # 2K literals
    levels = {1: lit}
    for n in range(2, length + 1):
        blocks = []
        for i in range(1, n):
            a, b = levels[i], levels[n - i]
            # (|a|, 1, M) op (1, |b|, M) -> (|a|*|b|, M), both operators
            blocks.append((a[:, None, :] & b[None, :, :]).reshape(-1, M))
            blocks.append((a[:, None, :] | b[None, :, :]).reshape(-1, M))
        levels[n] = np.unique(np.concatenate(blocks, axis=0), axis=0)
    return levels


def _max_iou(masks, neuron):
    inter = (masks & neuron).sum(axis=1).astype(np.float64)
    union = (masks | neuron).sum(axis=1).astype(np.float64)
    iou = np.divide(inter, union, out=np.zeros_like(inter), where=union > 0)
    return float(iou.max())


def best_iou_bruteforce(dense, neuron, length, chunk=64):
    """Max IoU over the entire enumerated space, by plain numpy. No search code involved.

    The top level is STREAMED rather than materialised: at length 4 the full level is
    ~1.26M masks x 24,199 elements = ~30 GB as bool. Streaming in chunks keeps peak memory
    at a few hundred MB and does not change the result, since only the max is needed.
    """
    levels = enumerate_masks(dense, length - 1) if length > 1 else {1: None}
    best, total = 0.0, 0
    for n, masks in (levels.items() if length > 1 else []):
        total += len(masks)
        best = max(best, _max_iou(masks, neuron))
    if length == 1:
        lit = np.concatenate([dense, ~dense], axis=0)
        return _max_iou(lit, neuron), len(lit)

    M = dense.shape[1]
    for i in range(1, length):
        a, b = levels[i], levels[length - i]
        for s in range(0, len(a), chunk):
            blk = a[s:s + chunk]
            both = np.concatenate([
                (blk[:, None, :] & b[None, :, :]).reshape(-1, M),
                (blk[:, None, :] | b[None, :, :]).reshape(-1, M)], axis=0)
            total += len(both)
            best = max(best, _max_iou(both, neuron))
    return best, total


def run_case(label, dense, concepts, neuron, length):
    oracle, n_forms = best_iou_bruteforce(dense, neuron, length)
    res = rts.run_one(dense, neuron, length, cap=200000, time_budget=1500,
                      beam_cap=None, concepts=concepts)
    search = res["best_iou"]
    # run_one rounds to 4dp for the CSV; recover full precision from the counts it kept.
    exact = res["n_inter"] / (res["n_fires"] + int(neuron.sum()) - res["n_inter"])
    ok = abs(exact - oracle) < 1e-12
    print(f"\n--- {label} (length {length}) ---")
    print(f"  masks evaluated           : {n_forms:,} (top level streamed, not deduped)")
    print(f"  brute-force max IoU       : {oracle!r}")
    print(f"  search best_iou           : {exact!r}")
    print(f"  search formula            : {res['formula']}")
    print(f"  |difference|              : {abs(exact - oracle):.3e}")
    print(f"  {'MATCH' if ok else 'MISMATCH -- STOP, do not adjust anything'}")
    if exact > oracle + 1e-12:
        print("  !! search exceeded the oracle: the enumeration is not a superset")
    return ok


def main():
    length = int(os.environ.get("ORACLE_LENGTH", "3"))
    toks = rtm.load_tokens(FEATS, 2000)
    concepts = rtm.select_concepts(toks, rtm.CATEGORIES, 15, 5)
    dense = rtm.build_dense(toks, concepts)
    print(f"K={len(concepts)} M={dense.shape[1]}  length={length}")

    cases = []
    for arm, path, unit in (("trained", "results/acts2k_trained_a0.1.npz", 88),
                            ("untrained", "results/acts2k_untrained_a0.1.npz", 92)):
        z = np.load(path)
        cases.append((f"{arm} unit{unit} a=0.1", z["acts"][unit].astype(bool)))
    proxy, ks = rts.make_proxy_neuron(dense, np.random.default_rng(999), 0.05)
    cases.append(("proxy neuron", proxy))

    ok = [run_case(lab, dense, concepts, n, length) for lab, n in cases]
    print("\nRESULT:", "PASS" if all(ok) else "FAIL")
    return 0 if all(ok) else 1


if __name__ == "__main__":
    raise SystemExit(main())
